language: swift
osx_image: xcode13.3
before_install:
- gem install cocoapods
- pod repo update
- pod install
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace KPS.xcworkspace -scheme KPS -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.2,name=iPhone 12" | xcpretty ONLY_ACTIVE_ARCH=YES
